routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Str;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//#Admin
Route::get('/admin', function () {
    return view('layouts.main-layout-admin');
});

//sementara dashboard admin
Route::get('/', function () {
    return view('contents.dashboard.dashboardAdmin');
});


Route::resource('dashboard', DashboardController::class);
Route::resource('kelas', KelasController::class);
Route::resource('siswa', SiswaController::class);
Route::resource('guru', GuruController::class);

app/Models/Guru.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Guru extends Model
{
    use HasFactory;
    protected $fillable = [
        'nip',
        'nama_guru',
        'jenis_kelamin_guru',
        'almaat_guru',
        'tgl_lahir_guru',
        'no_telpon_guru',
        'jarak_rumah_guru',
        'alat_transportasi',
    ];
}

app/Http/Controllers/GuruController.php
<?php

namespace App\Http\Controllers;

use App\Models\Guru;
use Illuminate\Http\Request;

class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('contents.guru.list');
        //menampilkan  all guru
        // $gurus = Guru::latest()->get();
        // return view('contents.guru.list')->with([
        //     'gurus' => $gurus
        // ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function show(Guru $guru)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function edit(Guru $guru)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Guru $guru)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Guru  $guru
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guru $guru)
    {
        //
    }
}

resources/views/contents/guru/create.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Input Data Guru</h5>
            <hr>
            <form class="row g-3" method="post" action="{{ route('guru.store') }}">
                @csrf
                <!-- Form Guru -->
                <div class="col-md-6">
                    <label for="nip" class="form-label">NIP</label>
                    <input type="text" class="form-control" id="nip" name="nip">
                </div>
                <div class="col-md-6">
                    <label for="nik" class="form-label">NIK</label>
                    <input type="text" class="form-control" id="nik" name="nik">
                </div>
                <div class="col-md-12">
                    <label for="nama_guru" class="form-label">Nama Lengkap</label>
                    <input type="text" class="form-control" id="nama_guru" name="nama_guru"
                        placeholder="sesuai akta kelahiran">
                </div>
                <div class="col-md-4">
                    <label for="jenis_kelamin" class="form-label">Jenis Kelamin</label>
                    <select id="jenis_kelamin" name="jenis_kelamin" class="form-select">
                        <option selected>- Pilih -</option>
                        <option value="L">Laki-laki</option>
                        <option value="P">Perempuan</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tempat_lahir" class="form-label">Tempat Lahir</label>
                    <select id="tempat_lahir" name="tempat_lahir" class="form-select">
                        <option selected>- Pilih -</option>
                        <option value="Sidoarjo">Sidoarjo</option>
                        <option value="Mojokerto">Mojokerto</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tgl_lahir" class="form-label">Tgl Lahir</label>
                    <input type="date" class="form-control" name="tgl_lahir">
                </div>
                <div class="col-md-6">
                    <label for="agama" class="form-label">Agama</label>
                    <select id="agama" class="form-select" name="agama">
                        <option>- Pilih -</option>
                        <option value="Islam">Islam</option>
                        <option value="Kristen Katolik">Kristen Katolik</option>
                        <option value="Kristen Protestan">Kristen Protestan</option>
                        <option value="Hindu">Hindu</option>
                        <option value="Budha">Budha</option>
                        <option value="Konghucu">Konghucu</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="no_telpon_siswa" class="form-label">No. Telpon/Hp Siswa</label>
                    <input type="text" class="form-control" id="no_telpon_siswa" name="no_telpon_siswa"
                        placeholder="089606769465">
                </div>
                <div class="col-md-6">
                    <label for="jarak_rumah" class="form-label">Jarak dari rumah ke sekolah (KM)</label>
                    <input type="text" class="form-control" id="jarak_rumah" name="jarak_rumah">
                </div>
                <div class="col-md-6">
                    <label for="alat_transportasi" class="form-label">Alat Transportasi</label>
                    <select id="alat_transportasi" class="form-select" name="alat_transportasi">
                        <option>- Pilih -</option>
                        <option value="Naik kendaraan umum">Naik kendaraan umum</option>
                        <option value="Naik kendaraan pribadi">Naik kendaraan pribadi</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/contents/guru/list.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <!-- Notifikasi dengan Alert -->
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif

                @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ session('error') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Data Guru</h5>
                        <a href="{{ route('guru.create') }}"><button type="button" class="btn btn-primary btn-xl"> <i
                                    class="bi-person-plus"></i>
                                Tambah Guru Baru</button></a>
                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">NIP</th>
                                    <th scope="col">Nama Lengkap</th>
                                    <th scope="col">Jenis Kelamin</th>
                                    <th scope="col">Alamat</th>
                                    <th scope="col">Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                {{-- <?php $no = 1; ?>
                                @foreach ($gurus as $guru)
                                    <tr>
                                        <th scope="row">{{ $no++ }}</th>
                                        <td>{{ $guru->nip }}</td>
                                        <td>{{ $guru->nama_guru }}</td>
                                        <td>{{ $guru->jenis_kelamin_guru }}</td>
                                        <td>{{ $guru->alamat_guru }}</td>
                                        <td>
                                            <div>
                                                <a href="{{ route('guru.edit', $guru->id) }}" class="btn btn-warning"><i
                                                        class="bi bi-pencil"></i></a>
                                                <button type="button" class="btn btn-dark"><i class="bi bi-eye"><a
                                                            href="{{ route('guru.show', $guru->id) }}"></a></i></button>

                                                <form onsubmit="return confirm('Apakah Anda Yakin?');"
                                                    action="{{ route('guru.destroy', $guru->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger"><i
                                                            class="bi bi-trash2"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach --}}
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection