routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Str;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//#Admin
Route::get('/admin', function () {
    return view('layouts.main-layout-admin');
});

//sementara dashboard admin
Route::get('/', function () {
    return view('contents.dashboard.dashboardAdmin');
});


Route::resource('dashboard', DashboardController::class);
Route::resource('kelas', KelasController::class);
Route::resource('siswa', SiswaController::class);
Route::resource('guru', GuruController::class);

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $fillable = [
        //data pribadi
        'status_siswa',
        'tgl_kelulusan',
        'nisn',
        'nik',
        'no_akta',
        'nama_siswa',
        'jenis_kelamin',
        'tempat_lahir',
        'tgl_lahir',
        'agama',
        'no_telpon_siswa',
        'jarak_rumah',
        'alat_transportasi',
        //data ayah
        'nama_ayah',
        'tempat_lahir_ayah',
        'tgl_lahir_ayah',
        'pendidikan_ayah',
        'pekerjaan_ayah',
        'penghasilan_ayah',
        //data ibu
        'nama_ibu',
        'tempat_lahir_ibu',
        'tgl_lahir_ibu',
        'pendidikan_ibu',
        'pekerjaan_ibu',
        'penghasilan_ibu',
        //data wali
        'nama_wali',
        'tempat_lahir_wali',
        'tgl_lahir_wali',
        'pendidikan_wali',
        'pekerjaan_wali',
        'penghasilan_wali',
        'jenis_tempat_tinggal',
        'provinsi',
        'kabupaten',
        'kecamatan',
        'kode_pos',
        'alamat'
    ];
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //menampilkan  all siswa
        $siswas = Siswa::latest()->get();
        return view('contents.siswa.list')->with([
            'siswas' => $siswas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contents.siswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validasi inputan
        $this->validate($request, [
            //data pribadi
            'status_siswa' => 'required',
            'tgl_kelulusan' => 'required',
            'nisn' => 'required',
            'nik' => 'required',
            'no_akta' => 'required',
            'nama_siswa' => 'required',
            'jenis_kelamin' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'agama' => 'required',
            'no_telpon_siswa' => 'required',
            'jarak_rumah' => 'required',
            'alat_transportasi' => 'required',
            //data ayah
            'nama_ayah' => 'required',
            'tempat_lahir_ayah' => 'required',
            'tgl_lahir_ayah' => 'required',
            'pendidikan_ayah' => 'required',
            'pekerjaan_ayah' => 'required',
            'penghasilan_ayah' => 'required',
            //data ibu
            'nama_ibu' => 'required',
            'tempat_lahir_ibu' => 'required',
            'tgl_lahir_ibu' => 'required',
            'pendidikan_ibu' => 'required',
            'pekerjaan_ibu' => 'required',
            'penghasilan_ibu' => 'required',
            //data wali
            'nama_wali' => 'required',
            'tempat_lahir_wali' => 'required',
            'tgl_lahir_wali' => 'required',
            'pendidikan_wali' => 'required',
            'pekerjaan_wali' => 'required',
            'penghasilan_wali' => 'required',
            'jenis_tempat_tinggal' => 'required',
            'provinsi' => 'required',
            'kabupaten' => 'required',
            'kecamatan' => 'required',
            'kode_pos' => 'required',
            'alamat' => 'required',
        ]);

        //proses save data
        $storeSiswa = Siswa::create([
            //data pribadi
            'status_siswa' => $request->status_siswa,
            'tgl_kelulusan' => $request->tgl_kelulusan,
            'nisn' => $request->nisn,
            'nik' => $request->nik,
            'no_akta' => $request->no_akta,
            'nama_siswa' => $request->nama_siswa,
            'jenis_kelamin' => $request->jenis_kelamin,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->tgl_lahir,
            'agama' => $request->agama,
            'no_telpon_siswa' => $request->no_telpon_siswa,
            'jarak_rumah' => $request->jarak_rumah,
            'alat_transportasi' => $request->alat_transportasi,
            //data ayah
            'nama_ayah' => $request->nama_ayah,
            'tempat_lahir_ayah' => $request->tempat_lahir_ayah,
            'tgl_lahir_ayah' => $request->tgl_lahir_ayah,
            'pendidikan_ayah' => $request->pendidikan_ayah,
            'pekerjaan_ayah' => $request->pekerjaan_ayah,
            'penghasilan_ayah' => $request->penghasilan_ayah,
            //data ibu
            'nama_ibu' => $request->nama_ibu,
            'tempat_lahir_ibu' => $request->tempat_lahir_ibu,
            'tgl_lahir_ibu' => $request->tgl_lahir_ibu,
            'pendidikan_ibu' => $request->pendidikan_ibu,
            'pekerjaan_ibu' => $request->pekerjaan_ibu,
            'penghasilan_ibu' => $request->penghasilan_ibu,
            //data wali
            'nama_wali' => $request->nama_wali,
            'tempat_lahir_wali' => $request->tempat_lahir_wali,
            'tgl_lahir_wali' => $request->tgl_lahir_wali,
            'pendidikan_wali' => $request->pendidikan_wali,
            'pekerjaan_wali' => $request->pekerjaan_wali,
            'penghasilan_wali' => $request->penghasilan_wali,
            'jenis_tempat_tinggal' => $request->jenis_tempat_tinggal,
            'provinsi' => $request->provinsi,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'kode_pos' => $request->kode_pos,
            'alamat' => $request->kode_pos,
        ]);

        // dd($storeSiswa);

        //kondisi jika save berhasil atau tidak
        if ($storeSiswa) {
            return redirect()
                ->route('siswa.index')
                ->with([
                    'success' =>  "Berhasil menyimpan data siswa !"
                ]);
        } else {
            return redirect()
                ->back()
                ->withInput()
                ->with([
                    'error' => 'Gagal menyimpan data siswa!'
                ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function show(Siswa $siswa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);
        return view('contents.siswa.edit', compact('siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validasi inputan
        $this->validate($request, [
            //data pribadi
            'status_siswa' => 'required',
            'tgl_kelulusan' => 'required',
            'nisn' => 'required',
            'nik' => 'required',
            'no_akta' => 'required',
            'nama_siswa' => 'required',
            'jenis_kelamin' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'agama' => 'required',
            'no_telpon_siswa' => 'required',
            'jarak_rumah' => 'required',
            'alat_transportasi' => 'required',
            //data ayah
            'nama_ayah' => 'required',
            'tempat_lahir_ayah' => 'required',
            'tgl_lahir_ayah' => 'required',
            'pendidikan_ayah' => 'required',
            'pekerjaan_ayah' => 'required',
            'penghasilan_ayah' => 'required',
            //data ibu
            'nama_ibu' => 'required',
            'tempat_lahir_ibu' => 'required',
            'tgl_lahir_ibu' => 'required',
            'pendidikan_ibu' => 'required',
            'pekerjaan_ibu' => 'required',
            'penghasilan_ibu' => 'required',
            //data wali
            'nama_wali' => 'required',
            'tempat_lahir_wali' => 'required',
            'tgl_lahir_wali' => 'required',
            'pendidikan_wali' => 'required',
            'pekerjaan_wali' => 'required',
            'penghasilan_wali' => 'required',
            'jenis_tempat_tinggal' => 'required',
            'provinsi' => 'required',
            'kabupaten' => 'required',
            'kecamatan' => 'required',
            'kode_pos' => 'required',
            'alamat' => 'required'
        ]);

        $siswaUpdate = Siswa::findOrFail($id);

        $siswaUpdate->update([
            //data pribadi
            'status_siswa' => $request->status_siswa,
            'tgl_kelulusan' => $request->tgl_kelulusan,
            'nisn' => $request->nisn,
            'nik' => $request->nik,
            'no_akta' => $request->no_akta,
            'nama_siswa' => $request->nama_siswa,
            'jenis_kelamin' => $request->jenis_kelamin,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->tgl_lahir,
            'agama' => $request->agama,
            'no_telpon_siswa' => $request->no_telpon_siswa,
            'jarak_rumah' => $request->jarak_rumah,
            'alat_transportasi' => $request->alat_transportasi,
            //data ayah
            'nama_ayah' => $request->nama_ayah,
            'tempat_lahir_ayah' => $request->tempat_lahir_ayah,
            'tgl_lahir_ayah' => $request->tgl_lahir_ayah,
            'pendidikan_ayah' => $request->pendidikan_ayah,
            'pekerjaan_ayah' => $request->pekerjaan_ayah,
            'penghasilan_ayah' => $request->penghasilan_ayah,
            //data ibu
            'nama_ibu' => $request->nama_ibu,
            'tempat_lahir_ibu' => $request->tempat_lahir_ibu,
            'tgl_lahir_ibu' => $request->tgl_lahir_ibu,
            'pendidikan_ibu' => $request->pendidikan_ibu,
            'pekerjaan_ibu' => $request->pekerjaan_ibu,
            'penghasilan_ibu' => $request->penghasilan_ibu,
            //data wali
            'nama_wali' => $request->nama_wali,
            'tempat_lahir_wali' => $request->tempat_lahir_wali,
            'tgl_lahir_wali' => $request->tgl_lahir_wali,
            'pendidikan_wali' => $request->pendidikan_wali,
            'pekerjaan_wali' => $request->pekerjaan_wali,
            'penghasilan_wali' => $request->penghasilan_wali,
            'jenis_tempat_tinggal' => $request->jenis_tempat_tinggal,
            'provinsi' => $request->provinsi,
            'kabupaten' => $request->kabupaten,
            'kecamatan' => $request->kecamatan,
            'kode_pos' => $request->kode_pos,
            'alamat' => $request->kode_pos,
        ]);

resources/views/contents/siswa/create.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Input Data Pribadi Siswa</h5>
            <hr>
            <form class="row g-3" method="post" action="{{ route('siswa.store') }}">
                @csrf
                <!-- Form Siswa -->
                <div class="col-md-6">
                    <label for="status_siswa" class="form-label">Status Siswa</label>
                    <select id="status_siswa" name="status_siswa" class="form-select">
                        <option selected>- Pilih -</option>
                        <option value="aktif">aktif</option>
                        <option value="nonaktif">nonaktif</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="tgl_kelulusan" class="form-label">Tgl Kelulusan</label>
                    <input type="date" class="form-control" name="tgl_kelulusan">
                </div>
                <div class="col-md-4">
                    <label for="nisn" class="form-label">NISN</label>
                    <input type="text" class="form-control" id="nisn" name="nisn">
                </div>
                <div class="col-md-4">
                    <label for="nik" class="form-label">NIK</label>
                    <input type="text" class="form-control" id="nik" name="nik">
                </div>
                <div class="col-md-4">
                    <label for="no_akta" class="form-label">Nomor Akta</label>
                    <input type="text" class="form-control" id="no_akta" name="no_akta">
                </div>
                <div class="col-md-12">
                    <label for="nama_siswa" class="form-label">Nama Lengkap</label>
                    <input type="text" class="form-control" id="nama_siswa" name="nama_siswa"
                        placeholder="sesuai akta kelahiran">
                </div>
                <div class="col-md-4">
                    <label for="jenis_kelamin" class="form-label">Jenis Kelamin</label>
                    <select id="jenis_kelamin" name="jenis_kelamin" class="form-select">
                        <option selected>- Pilih -</option>
                        <option value="L">Laki-laki</option>
                        <option value="P">Perempuan</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tempat_lahir" class="form-label">Tempat Lahir</label>
                    <select id="tempat_lahir" name="tempat_lahir" class="form-select">
                        <option selected>- Pilih -</option>
                        <option value="Sidoarjo">Sidoarjo</option>
                        <option value="Mojokerto">Mojokerto</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tgl_lahir" class="form-label">Tgl Lahir</label>
                    <input type="date" class="form-control" name="tgl_lahir">
                </div>
                <div class="col-md-6">
                    <label for="agama" class="form-label">Agama</label>
                    <select id="agama" class="form-select" name="agama">
                        <option>- Pilih -</option>
                        <option value="Islam">Islam</option>
                        <option value="Kristen Katolik">Kristen Katolik</option>
                        <option value="Kristen Protestan">Kristen Protestan</option>
                        <option value="Hindu">Hindu</option>
                        <option value="Budha">Budha</option>
                        <option value="Konghucu">Konghucu</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="no_telpon_siswa" class="form-label">No. Telpon/Hp Siswa</label>
                    <input type="text" class="form-control" id="no_telpon_siswa" name="no_telpon_siswa"
                        placeholder="089606769465">
                </div>
                <div class="col-md-6">
                    <label for="jarak_rumah" class="form-label">Jarak dari rumah ke sekolah (KM)</label>
                    <input type="text" class="form-control" id="jarak_rumah" name="jarak_rumah">
                </div>
                <div class="col-md-6">
                    <label for="alat_transportasi" class="form-label">Alat Transportasi</label>
                    <select id="alat_transportasi" class="form-select" name="alat_transportasi">
                        <option>- Pilih -</option>
                        <option value="Naik kendaraan umum">Naik kendaraan umum</option>
                        <option value="Naik kendaraan pribadi">Naik kendaraan pribadi</option>
                    </select>
                </div>
                <!-- End Form Siswa-->

                <!-- Form Ayah -->
                <h5 class="card-title">Data Ayah</h5>
                <hr>
                <div class="col-md-12">
                    <label for="nama_ayah" class="form-label">Nama Lengkap</label>
                    <input type="text" class="form-control" id="nama_ayah" name="nama_ayah"
                        placeholder="sesuai akta kelahiran">
                </div>
                <div class="col-md-4">
                    <label for="tempat_lahir_ayah" class="form-label">Tempat Lahir</label>
                    <select id="tempat_lahir_ayah" name="tempat_lahir_ayah" class="form-select">
                        <option>- Pilih -</option>
                        <option value="Sidoarjo">Sidoarjo</option>
                        <option value="Mojokerto">Mojokerto</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tgl_lahir_ayah" class="form-label">Tgl Lahir</label>
                    <input type="date" class="form-control" name="tgl_lahir_ayah">
                </div>
                <div class="col-md-4">
                    <label for="pendidikan_ayah" class="form-label">Pendidikan Ayah</label>
                    <input type="text" class="form-control" id="pendidikan_ayah" name="pendidikan_ayah">
                </div>
                <div class="col-md-6">
                    <label for="pekerjaan_ayah" class="form-label">Pekerjaan Ayah</label>
                    <input type="text" class="form-control" id="pekerjaan_ayah" name="pekerjaan_ayah">
                </div>
                <div class="col-md-6">
                    <label for="penghasilan_ayah" class="form-label">Penghasilan (Rp)</label>
                    <input type="text" class="form-control" id="penghasilan_ayah" name="penghasilan_ayah"
                        placeholder="contoh : 3500000">
                </div>
                <!-- End Form Ayah-->

                <!-- Form Ibu -->
                <h5 class="card-title">Data Ibu</h5>
                <hr>
                <div class="col-md-12">
                    <label for="nama_ibu" class="form-label">Nama Lengkap</label>
                    <input type="text" class="form-control" id="nama_ibu" name="nama_ibu"
                        placeholder="sesuai akta kelahiran">
                </div>
                <div class="col-md-4">
                    <label for="tempat_lahir_ibu" class="form-label">Tempat Lahir</label>
                    <select id="tempat_lahir_ibu" name="tempat_lahir_ibu" class="form-select">
                        <option>- Pilih -</option>
                        <option value="Sidoarjo">Sidoarjo</option>
                        <option value="Mojokerto">Mojokerto</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tgl_lahir_ibu" class="form-label">Tgl Lahir</label>
                    <input type="date" class="form-control" name="tgl_lahir_ibu">
                </div>
                <div class="col-md-4">
                    <label for="pendidikan_ibu" class="form-label">Pendidikan ibu</label>
                    <input type="text" class="form-control" id="pendidikan_ibu" name="pendidikan_ibu">
                </div>
                <div class="col-md-6">
                    <label for="pekerjaan_ibu" class="form-label">Pekerjaan Ibu</label>
                    <input type="text" class="form-control" id="pekerjaan_ibu" name="pekerjaan_ibu">
                </div>
                <div class="col-md-6">
                    <label for="penghasilan_ibu" class="form-label">Penghasilan (Rp)</label>
                    <input type="text" class="form-control" id="penghasilan_ibu" name="penghasilan_ibu"
                        placeholder="contoh : 3500000">
                </div>
                <!-- End Form Ibu-->

                <!-- Form Wali -->
                <h5 class="card-title">Data Wali</h5>
                <hr>
                <div class="col-md-12">
                    <label for="nama_wali" class="form-label">Nama Lengkap</label>
                    <input type="text" class="form-control" id="nama_wali" name="nama_wali"
                        placeholder="sesuai akta kelahiran">
                </div>
                <div class="col-md-4">
                    <label for="tempat_lahir_wali" class="form-label">Tempat Lahir</label>
                    <select id="tempat_lahir_wali" name="tempat_lahir_wali" class="form-select">
                        <option selected>- Pilih -</option>
                        <option value="Sidoarjo">Sidoarjo</option>
                        <option value="Mojokerto">Mojokerto</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="tgl_lahir_wali" class="form-label">Tgl Lahir</label>
                    <input type="date" class="form-control" name="tgl_lahir_wali">
                </div>
                <div class="col-md-4">
                    <label for="pendidikan_wali" class="form-label">Pendidikan wali</label>
                    <input type="text" class="form-control" id="pendidikan_wali" name="pendidikan_wali">
                </div>
                <div class="col-md-6">
                    <label for="pekerjaan_wali" class="form-label">Pekerjaan wali</label>
                    <input type="text" class="form-control" id="pekerjaan_wali" name="pekerjaan_wali">
                </div>
                <div class="col-md-6">
                    <label for="penghasilan_wali" class="form-label">Penghasilan (Rp)</label>
                    <input type="text" class="form-control" id="penghasilan_wali" name="penghasilan_wali"
                        placeholder="contoh : 3500000">
                </div>
                <div class="col-md-4">
                    <label for="jenis_tempat_tinggal" class="form-label">Jenis Tempat Tinggal</label>
                    <select id="jenis_tempat_tinggal" name="jenis_tempat_tinggal" class="form-select">
                        <option>- Pilih -</option>
                        <option value="Sewa">Sewa</option>
                        <option value="Pribadi">Pribadi</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="provinsi" class="form-label">Provinsi</label>
                    <select id="provinsi" name="provinsi" class="form-select">
                        <option>- Pilih -</option>
                        <option value="Jawa Timur">Jawa Timur</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="kabupaten" class="form-label">Kabupaten</label>
                    <select id="kabupaten" name="kabupaten" class="form-select">
                        <option>- Pilih -</option>
                        <option value="Sidoarjo">Sidoarjo</option>
                        <option value="Mojokerto">Mojokerto</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label for="kecamatan" class="form-label">Kecamatan</label>
                    <select id="kecamatan" name="kecamatan" class="form-select">
                        <option>- Pilih -</option>
                        <option value="Krian">Krian</option>

                    </select>
                </div>
                <div class="col-md-6">
                    <label for="kode_pos" class="form-label">Kode Pos</label>
                    <input type="text" class="form-control" id="kode_pos" name="kode_pos">
                </div>
                <div class="col-md-12">
                    <label for="alamat" class="form-label">Alamat</label>
                    <input type="text" class="form-control" id="alamat" name="alamat">
                </div>

                <!-- End Form Wali-->
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/contents/siswa/list.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <!-- Notifikasi dengan Alert -->
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif

                @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ session('error') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Data Siswa</h5>
                        <a href="{{ route('siswa.create') }}"><button type="button" class="btn btn-success btn-xl"> <i
                                    class="bi-person-plus"></i>
                                Tambah Siswa Baru</button></a>
                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">NISN</th>
                                    <th scope="col">Nama Lengkap</th>
                                    <th scope="col">Jenis Kelamin</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no = 1; ?>
                                @foreach ($siswas as $siswa)
                                    <tr>
                                        <th scope="row">{{ $no++ }}</th>
                                        <td>{{ $siswa->nisn }}</td>
                                        <td>{{ $siswa->nama_siswa }}</td>
                                        <td>{{ $siswa->jenis_kelamin }}</td>
                                        <td>{{ $siswa->status_siswa }}</td>
                                        <td>
                                            <div>
                                                <a href="{{ route('siswa.edit', $siswa->id) }}" class="btn btn-warning"><i
                                                        class="bi bi-pencil"></i></a>
                                                <button type="button" class="btn btn-dark"><i class="bi bi-eye"><a
                                                            href="{{ route('siswa.show', $siswa->id) }}"></a></i></button>

                                                <form onsubmit="return confirm('Apakah Anda Yakin?');"
                                                    action="{{ route('siswa.destroy', $siswa->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger"><i
                                                            class="bi bi-trash2"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection