routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\SiswaController;
use Illuminate\Support\Str;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//#Admin
Route::get('/admin', function () {
    return view('layouts.main-layout-admin');
});

//sementara dashboard admin
Route::get('/', function () {
    return view('contents.dashboard.dashboardAdmin');
});


Route::resource('dashboard', DashboardController::class);
Route::resource('kelas', KelasController::class);
Route::resource('siswa', SiswaController::class);
Route::resource('guru', GuruController::class);

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama_kelas',
        'nama_wali_kelas',
    ];
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use Illuminate\Http\Request;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //menampilkan  all kelas
        $kelass = Kelas::latest()->get();
        return view('contents.kelas.list')->with([
            'kelass' => $kelass
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contents.kelas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi inputan
        $this->validate($request, [
            'nama_kelas' => 'required',
            'nama_wali_kelas' => 'required',
        ]);

        //save data
        $storeKelas = Kelas::create([
            'nama_kelas' => $request->nama_kelas,
            'nama_wali_kelas' => $request->nama_wali_kelas,
        ]);


        // dd($storeKelas);

        //kondisi jika save berhasil atau tidak
        if ($storeKelas) {
            return redirect()
                ->route('kelas.index')
                ->with([
                    'success' =>  "Berhasil menyimpan data kelas !"
                ]);
        } else {
            return redirect()
                ->back()
                ->withInput()
                ->with([
                    'error' => 'Gagal menyimpan data kelas!'
                ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //menampilkan edit data
        $kelas = Kelas::findOrFail($id);
        return view('contents.kelas.edit', compact('kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validasi inputan
        $this->validate($request, [
            'nama_kelas' => 'required',
            'nama_wali_kelas' => 'required',
        ]);

        $kelasUpdate = Kelas::findOrFail($id);

        //udpate data
        $kelasUpdate->update([
            'nama_kelas' => $request->nama_kelas,
            'nama_wali_kelas' => $request->nama_wali_kelas,
        ]);




        // dd($updateKelas);

        //kondisi jika save berhasil atau tidak
        if ($kelasUpdate) {
            return redirect()
                ->route('kelas.index')
                ->with([
                    'success' =>  "Berhasil update data kelas !"
                ]);
        } else {
            return redirect()
                ->back()
                ->withInput()
                ->with([
                    'error' => 'Gagal update data kelas!'
                ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kelas = Kelas::findOrFail($id);
        $kelas->delete();

        if ($kelas) {
            return redirect()
                ->route('kelas.index')
                ->with([
                    'success' => 'Data Kelas Berhasil Dihapus !'
                ]);
        } else {
            return redirect()
                ->route('kelas.index')
                ->with([
                    'error' => 'Data kelas Gagal Dihapus !'
                ]);
        }
    }
}

resources/views/contents/kelas/create.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Input Data Kelas</h5>
            <hr>
            <form class="row g-3" method="POST" action="{{ route('kelas.store') }}">
                @csrf
                <!-- Form Guru -->
                <div class="col-md-6">
                    <label for="nama_kelas" class="form-label">Nama Kelas</label>
                    <input type="text" class="form-control" id="nama_kelas" name="nama_kelas">
                </div>
                <div class="col-md-6">
                    <label for="nama_wali_kelas" class="form-label">Wali Kelas</label>
                    <input type="text" class="form-control" id="nama_wali_kelas" name="nama_wali_kelas">
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>~
        </div>
    </div>
@endsection

resources/views/contents/kelas/edit.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit Data Kelas</h5>
            <hr>
            <form class="row g-3" method="POST" action="{{ route('kelas.update', $kelas->id) }}">
                @csrf
                @method('PUT')
                <!-- Form Guru -->
                <div class="col-md-6">
                    <label for="nama_kelas" class="form-label">Nama Kelas</label>
                    <input type="text" class="form-control" id="nama_kelas" name="nama_kelas"
                        value="{{ $kelas->nama_kelas }}">
                </div>
                <div class="col-md-6">
                    <label for="nama_wali_kelas" class="form-label">Wali Kelas</label>
                    <input type="text" class="form-control" id="nama_wali_kelas" name="nama_wali_kelas"
                        value="{{ $kelas->nama_wali_kelas }}">
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form>~
        </div>
    </div>
@endsection

resources/views/contents/kelas/list.blade.php
@extends('layouts.main-layout-admin')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <!-- Notifikasi dengan Alert -->
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('success') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif

                @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ session('error') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Data Kelas</h5>
                        <a href="{{ route('kelas.create') }}"><button type="button" class="btn btn-success btn-xl"> <i
                                    class="bi-door-closed-fill"></i>
                                + Tambah Data Kelas Baru</button></a>
                        <!-- Table with stripped rows -->
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">Nama Kelas</th>
                                    <th scope="col">Wali kelas</th>
                                    <th scope="col">Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no = 1; ?>
                                @foreach ($kelass as $kelas)
                                    <tr>
                                        <th scope="row">{{ $no++ }}</th>
                                        <td>{{ $kelas->nama_kelas }}</td>
                                        <td>{{ $kelas->nama_wali_kelas }}</td>
                                        <td>
                                            <div>
                                                <a href="{{ route('kelas.edit', $kelas->id) }}" class="btn btn-warning"><i
                                                        class="bi bi-pencil"></i></a>
                                                <button type="button" class="btn btn-dark"><i class="bi bi-eye"><a
                                                            href="{{ route('kelas.show', $kelas->id) }}"></a></i></button>

                                                <form onsubmit="return confirm('Apakah Anda Yakin?');"
                                                    action="{{ route('kelas.destroy', $kelas->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger"><i
                                                            class="bi bi-trash2"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <!-- End Table with stripped rows -->

                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection